- name: Execute Machine
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          SHRINKME_API: ${{ secrets.SHRINKME_API }}
          GEMINI_API: ${{ secrets.GEMINI_API }}
        run: python bot.py
