name: Super 30-Min Money Bot

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Execute Bot
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          BLOG_ID: ${{ secrets.BLOG_ID }}
          GEMINI_API: ${{ secrets.GEMINI_API }}
          SHRINKME_API: ${{ secrets.SHRINKME_API }}
        run: python bot.py
